eureka:
  instance:
    preferIpAddress: true
  client:
    region: default
    registryFetchIntervalSeconds: 30
    serviceUrl.defaultZone: http://localhost:8761/eureka/

logging.level.org.springframework.cloud.gateway: TRACE
management.endpoints.web.exposure.include: '*'

# https://cloud.spring.io/spring-cloud-static/spring-cloud-gateway/2.2.0.M3/reference/html/#configuring-predicates-and-filters-for-discoveryclient-routes
spring:
  application.name: cloud-gateway
  cloud.gateway:
      discovery.locator:
        enabled: true
        lower-case-service-id: true
      filter:
        circuit-breaker.enabled: true
