eureka.client:
  region: default
  registryFetchIntervalSeconds: 30
  serviceUrl.defaultZone: http://localhost:8761/eureka/

spring:
  config.import: optional:configserver:cloud-config
  application.name: test-rest
  cloud:
    config:
      discovery:
        enabled: true
        service-id: cloud-config
    discovery:
      enabled: true
