eureka.client:
  region: default
  registryFetchIntervalSeconds: 30
  serviceUrl.defaultZone: http://localhost:8761/eureka/

spring:
  config.import: 'optional:configserver:http://localhost:18888'
  application.name: test-rest
  kafka:
    client-id: ${spring.application.name}
    bootstrap-servers: 'srv-28-8.cl.dev.sbt:9092,srv-28-9.cl.dev.sbt:9092,srv-28-10.cl.dev.sbt:9092'
    consumer:
      group-id: 'ssd-${spring.application.name}'

  cloud:
    bus:
      enabled: true
    discovery.enabled: true

debug: true
